name: Build ELF

on:
  workflow_dispatch:
  push:
    paths:
  pull_request:
    
jobs:
  build-packages:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip

    - uses: actions/checkout@v2
    - run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git fetch --prune --unshallow
    
    - name: Compile
      run: |
        make -C launcher-hdd/payload/
        
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

        
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: SoftDev2-Launcher
        path: |
              launcher-hdd/payload/payload-stripped.elf
              launcher-hdd/payload/payload.bin       	
